version: "3.7"
services:
  node:
    image: nutsfoundation/nuts-node:master
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - 1323:1323
      - 5555:5555
    healthcheck:
      test: "curl -f http://localhost:1323/status || exit 1"
    volumes:
      - "./config/node/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./data/node:/opt/nuts/data"
  admin:
    image: nutsfoundation/nuts-registry-admin-demo:master
    ports:
      - 1303:1303
    healthcheck:
      test: "curl -f http://localhost:1303/status || exit 1"
    volumes:
      - "./config/admin/server.config.yaml:/app/server.config.yaml"
      - "./data/admin:/app/data"
  demo:
    image: nutsfoundation/nuts-demo-ehr:main
    ports:
      - 1304:1304
    healthcheck:
      test: "curl -f http://localhost:1304/status | exit 1"
    volumes:
      - "./config/demo/server.config.yaml:/app/server.config.yaml"
      - "./data/admin/customers.json:/app/customers.json:ro"
      - "./data/demo:/app/data"
  hapi:
    image: hapiproject/hapi:v5.4.1
    environment:
      hapi.fhir.fhir_version: DSTU3
      hapi.fhir.partitioning.allow_references_across_partitions: "false"
    expose:
      - 8080
    volumes:
      - "./data/hapi:/usr/local/tomcat/target"
