version: "3.7"
services:
#  discovery:
#    image: nutsfoundation/nuts-discovery:latest-dev
#    networks:
#      - nuts
  notary:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    volumes:
      - "./nodes/notary/:/opt/nuts/"
  bundy:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    volumes:
      - "./nodes/bundy/:/opt/nuts/"
  dahmer:
    image: nutsfoundation/nuts-consent-cordapp:latest-dev
    networks:
      - nuts
    volumes:
      - "./nodes/dahmer/:/opt/nuts/"
  bundy-bridge:
    image: nutsfoundation/nuts-consent-bridge:latest-dev
    environment:
      SPRING_SERVER_ADDRESS: bundy-bridge
    networks:
      - nuts
    ports:
      - "18080:8080"
    volumes:
      - "./config/bundy/application.properties:/opt/nuts/application.properties"
  dahmer-bridge:
    image: nutsfoundation/nuts-consent-bridge:latest-dev
    environment:
      SPRING_SERVER_ADDRESS: dahmer-bridge
    networks:
      - nuts
    ports:
      - "28080:8080"
    volumes:
      - "./config/dahmer/application.properties:/opt/nuts/application.properties"
  bundy-nuts-service-space:
    image: nutsfoundation/nuts-service-space:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    networks:
      nuts:
        aliases:
          - registry
    ports:
      - "11323:1323"
    volumes:
      - "./config/bundy/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./config/registry/:/opt/nuts/registry"
      - "./nodes/irma/:/opt/nuts/irma"
      - "./nodes/bundy/sqlite/:/opt/nuts/sqlite"
      - "./config/bundy/keys/:/opt/nuts/keys"
  dahmer-nuts-service-space:
    image: nutsfoundation/nuts-service-space:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    networks:
      nuts:
        aliases:
        - registry
    ports:
      - "21323:1323"
    volumes:
      - "./config/dahmer/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./config/registry/:/opt/nuts/registry"
      - "./nodes/irma/:/opt/nuts/irma"
      - "./nodes/dahmer/sqlite/:/opt/nuts/sqlite"
      - "./config/dahmer/keys/:/opt/nuts/keys"
networks:
  nuts:
    name: nuts