datadir: /opt/nuts/data
http:
  default:
    address: :1323
    cors:
      origin: "*"
verbosity: debug
network:
  truststorefile: /opt/nuts/ssl/ca.pem
  certfile: /opt/nuts/ssl/node.nuts.local.pem
  certkeyfile: /opt/nuts/ssl/node.nuts.local.key
  bootstrapnodes:
    - "nuts.reinkrul.nl:5555"