credentials:
  username: "demo@nuts.nl"
  password: "demo"
port: 1304
dbfile: /app/data/registry-admin.db
dbConnectionString : file:/app/data/ehr.db
customersfile: /app/customers.json
nutsnodeaddr: http://node:1323
fhirserveraddr: http://hapi:8080/fhir
